#Fire up GraphLab Create

We always start with this line before using any part of GraphLab Create

In [1]:
import graphlab

A newer version of GraphLab Create (v1.8.5) is available! Your current version is v1.8.3.

You can use pip to upgrade the graphlab-create package. For more information see https://dato.com/products/create/upgrade.


#Load a tabular data set

In [2]:
sf = graphlab.SFrame('C:\machineLearn_washingtonU_cousera\case study\people-example.csv')

[INFO] GraphLab Create v1.8.3 started. Logging: C:\Users\Gloria\AppData\Local\Temp\graphlab_server_1461345047.log.0


Finished parsing file C:\machineLearn_washingtonU_cousera\case study\people-example.csv

Parsing completed. Parsed 7 lines in 0.03277 secs.

------------------------------------------------------
Inferred types from first line of file as 
column_type_hints=[str,str,str,long]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------


#SFrame basics

In [3]:
sf['Last Name', 'Country'][2:6]

Columns:
	Last Name	str
	Country	str

Rows: 4

Data:
+-----------+---------------+
| Last Name |    Country    |
+-----------+---------------+
|    Jone   |    England    |
|   Brown   |      USA      |
|   Cooper  |     Poland    |
|  Campbell | United States |
+-----------+---------------+
[4 rows x 2 columns]

In [4]:
sf['First Name'] #we can view first few lines of table

dtype: str
Rows: 7
['Bob', 'Alice', 'Malcolm', 'Felix', 'Alex', 'Tod', 'Derek']

In [5]:
for x in sf['First Name'] :
    print(x)


Bob
Alice
Malcolm
Felix
Alex
Tod
Derek


In [6]:
sf.tail()  # view end of the table

Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int

Rows: 7

Data:
+------------+-----------+---------------+-----+
| First Name | Last Name |    Country    | age |
+------------+-----------+---------------+-----+
|    Bob     |   Smith   | United States |  24 |
|   Alice    |  Williams |     Canada    |  23 |
|  Malcolm   |    Jone   |    England    |  22 |
|   Felix    |   Brown   |      USA      |  23 |
|    Alex    |   Cooper  |     Poland    |  23 |
|    Tod     |  Campbell | United States |  22 |
|   Derek    |    Ward   |  Switzerland  |  25 |
+------------+-----------+---------------+-----+
[7 rows x 4 columns]

# join test

In [7]:
animals = graphlab.SFrame({'id':[1,2,3,4], 
                            'name':['dog','cat','sheep','cow'] })
sounds = graphlab.SFrame({'id':[1,3,4,5],
                            'sound':['woof','baa','moo','oink']})
#animals.join(sounds, how='inner')   #If ‘None’ is given, join will use all columns that have the same name as the set of join keys.
#animals.join(sounds, on='id',how='left')
#animals.join(sounds, on='id',how='right')
print animals
print sounds
joined_animals = animals.join(sounds, on='id',how='inner')
print joined_animals

+----+-------+
| id |  name |
+----+-------+
| 1  |  dog  |
| 2  |  cat  |
| 3  | sheep |
| 4  |  cow  |
+----+-------+
[4 rows x 2 columns]

+----+-------+
| id | sound |
+----+-------+
| 1  |  woof |
| 3  |  baa  |
| 4  |  moo  |
| 5  |  oink |
+----+-------+
[4 rows x 2 columns]

+----+-------+-------+
| id |  name | sound |
+----+-------+-------+
| 1  |  dog  |  woof |
| 3  | sheep |  baa  |
| 4  |  cow  |  moo  |
+----+-------+-------+
[3 rows x 3 columns]



# Test SFrame array multiply

In [8]:
sf['updated_age'] = sf['age'].apply(lambda x: x**2)
sf.tail()

Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int
	updated_age	int

Rows: 7

Data:
+------------+-----------+---------------+-----+-------------+
| First Name | Last Name |    Country    | age | updated_age |
+------------+-----------+---------------+-----+-------------+
|    Bob     |   Smith   | United States |  24 |     576     |
|   Alice    |  Williams |     Canada    |  23 |     529     |
|  Malcolm   |    Jone   |    England    |  22 |     484     |
|   Felix    |   Brown   |      USA      |  23 |     529     |
|    Alex    |   Cooper  |     Poland    |  23 |     529     |
|    Tod     |  Campbell | United States |  22 |     484     |
|   Derek    |    Ward   |  Switzerland  |  25 |     625     |
+------------+-----------+---------------+-----+-------------+
[7 rows x 5 columns]

In [9]:
# x=sf['age']
# y=sf['updated_age']
# sf['last_age']=x.apply(lambda x: x+y)
# sf.head()   #run time error

#GraphLab Canvas

In [10]:
# If you want Canvas visualization to show up on this notebook, 
# rather than popping up a new window, add this line:
graphlab.canvas.set_target('ipynb')
sf['age'].show(view='Categorical')

#Inspect columns of dataset

In [11]:
sf['Country']

dtype: str
Rows: 7
['United States', 'Canada', 'England', 'USA', 'Poland', 'United States', 'Switzerland']

In [12]:
sf['age']

dtype: int
Rows: 7
[24L, 23L, 22L, 23L, 23L, 22L, 25L]

Some simple columnar operations

In [13]:
sf['age'].mean()

23.142857142857146

In [14]:
sf['age'].max()

25L

In [15]:
sf['age'].min()

22L

In [16]:
sf['age'].size()

7

In [17]:
sf['Full Name'] = sf['First Name'] + ' ' + sf['Last Name']

In [18]:
sf

Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int
	updated_age	int
	Full Name	str

Rows: 7

Data:
+------------+-----------+---------------+-----+-------------+----------------+
| First Name | Last Name |    Country    | age | updated_age |   Full Name    |
+------------+-----------+---------------+-----+-------------+----------------+
|    Bob     |   Smith   | United States |  24 |     576     |   Bob Smith    |
|   Alice    |  Williams |     Canada    |  23 |     529     | Alice Williams |
|  Malcolm   |    Jone   |    England    |  22 |     484     |  Malcolm Jone  |
|   Felix    |   Brown   |      USA      |  23 |     529     |  Felix Brown   |
|    Alex    |   Cooper  |     Poland    |  23 |     529     |  Alex Cooper   |
|    Tod     |  Campbell | United States |  22 |     484     |  Tod Campbell  |
|   Derek    |    Ward   |  Switzerland  |  25 |     625     |   Derek Ward   |
+------------+-----------+---------------+-----+-------------+----------------+
[7 rows x 6 columns]

In [19]:
sf['new column']=1   # If there is no 'new column' create 'new column'
sf

Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int
	updated_age	int
	Full Name	str
	new column	int

Rows: 7

Data:
+------------+-----------+---------------+-----+-------------+----------------+
| First Name | Last Name |    Country    | age | updated_age |   Full Name    |
+------------+-----------+---------------+-----+-------------+----------------+
|    Bob     |   Smith   | United States |  24 |     576     |   Bob Smith    |
|   Alice    |  Williams |     Canada    |  23 |     529     | Alice Williams |
|  Malcolm   |    Jone   |    England    |  22 |     484     |  Malcolm Jone  |
|   Felix    |   Brown   |      USA      |  23 |     529     |  Felix Brown   |
|    Alex    |   Cooper  |     Poland    |  23 |     529     |  Alex Cooper   |
|    Tod     |  Campbell | United States |  22 |     484     |  Tod Campbell  |
|   Derek    |    Ward   |  Switzerland  |  25 |     625     |   Derek Ward   |
+------------+-----------+---------------+-----+-------------+----------------+
+------------+
| new column |
+------------+
|     1      |
|     1      |
|     1      |
|     1      |
|     1      |
|     1      |
|     1      |
+------------+
[7 rows x 7 columns]

In [20]:
sf['new column']=sf['new column'].apply(lambda x: x+10)
sf

Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int
	updated_age	int
	Full Name	str
	new column	int

Rows: 7

Data:
+------------+-----------+---------------+-----+-------------+----------------+
| First Name | Last Name |    Country    | age | updated_age |   Full Name    |
+------------+-----------+---------------+-----+-------------+----------------+
|    Bob     |   Smith   | United States |  24 |     576     |   Bob Smith    |
|   Alice    |  Williams |     Canada    |  23 |     529     | Alice Williams |
|  Malcolm   |    Jone   |    England    |  22 |     484     |  Malcolm Jone  |
|   Felix    |   Brown   |      USA      |  23 |     529     |  Felix Brown   |
|    Alex    |   Cooper  |     Poland    |  23 |     529     |  Alex Cooper   |
|    Tod     |  Campbell | United States |  22 |     484     |  Tod Campbell  |
|   Derek    |    Ward   |  Switzerland  |  25 |     625     |   Derek Ward   |
+------------+-----------+---------------+-----+-------------+----------------+
+------------+
| new column |
+------------+
|     11     |
|     11     |
|     11     |
|     11     |
|     11     |
|     11     |
|     11     |
+------------+
[7 rows x 7 columns]

In [21]:
sf['double age']=sf['age'] * sf['age']

In [22]:
sf.show()

In [23]:
sf['age'].min()

22L

#Use the apply function to do a advance transformation of our data

In [24]:
sf['Country']

dtype: str
Rows: 7
['United States', 'Canada', 'England', 'USA', 'Poland', 'United States', 'Switzerland']

In [25]:
sf['Country'].show()

In [26]:
def transform_country(country):
    if country == 'USA':
        return 'United States'
    else:
        return country

In [27]:
transform_country('Brazil')

'Brazil'

In [28]:
transform_country('Brasil')

'Brasil'

In [29]:
transform_country('USA')

'United States'

In [30]:
sf['Country'].apply(transform_country)  #only this cell apply and then back to the original, which is not apply transform_country 

dtype: str
Rows: 7
['United States', 'Canada', 'England', 'United States', 'Poland', 'United States', 'Switzerland']

In [31]:
#each country string in sf['Country']is transferred 
sf['Country'] = sf['Country'].apply(transform_country)  # ever after this cell excuted, changed permanently

In [32]:
sf.show()

In [33]:
sa = graphlab.SArray([1,2,3])   # for loop in SFrame perfo issue, so use apply()
print sa.apply(lambda x: x*2)
print sa

[2L, 4L, 6L]
[1L, 2L, 3L]


In [ ]:
# test_1 = ['a','b','cx','ddd','gs']
# count1 = 0
# for e in test_1:
#     count1 += 1
# #     print e
#     print count1
tl = [1,2,3,4,5,8,10,11,12,13,14,15,16,20,23,24,30]
cc = 0
p_size =5
# p_size =4
limit = p_size
for start in xrange(len(tl)-1):
    diff = tl[start+1] - tl[start] 
    if diff == 1 and limit > 0 :
        cc +=1       
        print "increase:",cc,"start",start,"contents :",tl[start]," diff:",diff," limit:",limit   
        limit -= 1
    else :
        start += p_size
        limit = p_size
        if start < len(tl)-1:
            print "new start:",start,"contents :",tl[start]," diff:",diff," limit:",limit   
        

In [34]:
#in "Full Name" column, count number of "a" char(low,capital including, if none exist, return 0), create new column "char a count" and 
# write each row the number of a in each "char a count" column.
# sf['char a count']=0
# sf.head()
def count_a(full_name):
    count = 0
    for each in full_name :   #for each character in string 
        each = each.lower()  # make it to lower case 
        if each == 'a' :
            count +=1
    return count
sf['char a count'] = sf['Full Name'].apply(count_a)
sf.head()   

Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int
	updated_age	int
	Full Name	str
	new column	int
	double age	int
	char a count	int

Rows: 7

Data:
+------------+-----------+---------------+-----+-------------+----------------+
| First Name | Last Name |    Country    | age | updated_age |   Full Name    |
+------------+-----------+---------------+-----+-------------+----------------+
|    Bob     |   Smith   | United States |  24 |     576     |   Bob Smith    |
|   Alice    |  Williams |     Canada    |  23 |     529     | Alice Williams |
|  Malcolm   |    Jone   |    England    |  22 |     484     |  Malcolm Jone  |
|   Felix    |   Brown   | United States |  23 |     529     |  Felix Brown   |
|    Alex    |   Cooper  |     Poland    |  23 |     529     |  Alex Cooper   |
|    Tod     |  Campbell | United States |  22 |     484     |  Tod Campbell  |
|   Derek    |    Ward   |  Switzerland  |  25 |     625     |   Derek Ward   |
+------------+-----------+---------------+-----+-------------+----------------+
+------------+------------+--------------+
| new column | double age | char a count |
+------------+------------+--------------+
|     11     |    576     |      0       |
|     11     |    529     |      2       |
|     11     |    484     |      1       |
|     11     |    529     |      0       |
|     11     |    529     |      1       |
|     11     |    484     |      1       |
|     11     |    625     |      1       |
+------------+------------+--------------+
[7 rows x 9 columns]

In [35]:
print sf['age'].sum()
print sf['age'].mean()
print sf['age'].min()
print sf['age'].max()
print sf['age'].var()
print sf['age'].std()
print len(sf['age'])
#print sf['double age'].column_types()
sf['double age2'] = sf['double age'].astype(float)
#sf.column_types()
sf.head()

162
23.1428571429
22
25
0.979591836735
0.989743318611
7


Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int
	updated_age	int
	Full Name	str
	new column	int
	double age	int
	char a count	int
	double age2	float

Rows: 7

Data:
+------------+-----------+---------------+-----+-------------+----------------+
| First Name | Last Name |    Country    | age | updated_age |   Full Name    |
+------------+-----------+---------------+-----+-------------+----------------+
|    Bob     |   Smith   | United States |  24 |     576     |   Bob Smith    |
|   Alice    |  Williams |     Canada    |  23 |     529     | Alice Williams |
|  Malcolm   |    Jone   |    England    |  22 |     484     |  Malcolm Jone  |
|   Felix    |   Brown   | United States |  23 |     529     |  Felix Brown   |
|    Alex    |   Cooper  |     Poland    |  23 |     529     |  Alex Cooper   |
|    Tod     |  Campbell | United States |  22 |     484     |  Tod Campbell  |
|   Derek    |    Ward   |  Switzerland  |  25 |     625     |   Derek Ward   |
+------------+-----------+---------------+-----+-------------+----------------+
+------------+------------+--------------+-------------+
| new column | double age | char a count | double age2 |
+------------+------------+--------------+-------------+
|     11     |    576     |      0       |    576.0    |
|     11     |    529     |      2       |    529.0    |
|     11     |    484     |      1       |    484.0    |
|     11     |    529     |      0       |    529.0    |
|     11     |    529     |      1       |    529.0    |
|     11     |    484     |      1       |    484.0    |
|     11     |    625     |      1       |    625.0    |
+------------+------------+--------------+-------------+
[7 rows x 10 columns]

In [36]:
def FirstN_more_than_3char(firstname):
    return filter(lambda firstname : len(firstname) > 3, sf['First Name'])

In [37]:
FirstN_more_than_3char(sf['First Name'])

['Alice', 'Malcolm', 'Felix', 'Alex', 'Derek']

In [38]:
def transform_name2(firstname):
    return map(lambda firstname : 'Great Alice' if firstname == 'Alice' else firstname, sf['First Name'])

In [39]:
transform_name2(sf['First Name'])

['Bob', 'Great Alice', 'Malcolm', 'Felix', 'Alex', 'Tod', 'Derek']

In [40]:
import numpy as np
np_a1 = np.arange(9).reshape(3,3)
np_a2 = np.arange(3,12).reshape(3,3)
print np_a1
np_a1 = np.dot(np_a1,np_a2)
print np_a1
print np_a1[:,2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]
[ 30 102 174]


In [41]:
import math
print math.e*7
print 2.5*math.e*7
print 2.5* (2.718182)**(7)

19.0279727992
47.569931998
2740.87818441


In [42]:
tolerance = 2.5e7
print float(tolerance)

25000000.0


In [43]:
print np.arange(6)

[0 1 2 3 4 5]


In [44]:
import numpy as np
ar22 = np.arange(4).reshape(2,2)
ar33 = np.arange(2,6).reshape(2,2)
print ar22
print ar33
print "ar22*ar33 : \n",ar22*ar33
print np.sum(ar22*ar33)
a2= [[1,2],
     [3,4]]
b2=[[0,1],
    [2,3]]
nna2 = np.array(a2)
print "***\n",np.array(a2)*np.array(b2)
print np.dot(np.array(a2),np.array(b2))

[[0 1]
 [2 3]]
[[2 3]
 [4 5]]
ar22*ar33 : 
[[ 0  3]
 [ 8 15]]
26
***
[[ 0  2]
 [ 6 12]]
[[ 4  7]
 [ 8 15]]


In [45]:
tmp = graphlab.SArray([1., 2., 3.])
tmp_cubed = tmp.apply(lambda x: x**3)
print tmp
print tmp_cubed

[1.0, 2.0, 3.0]
[1.0, 8.0, 27.0]


In [46]:
# two SFrame my_predictions , tru_labels. if same elements ,then count++
sf['compare_age'] = sf['age'].apply(lambda x: x if x%2 == 0 else x+1)
sf.head()

sf.head()


Columns:
	First Name	str
	Last Name	str
	Country	str
	age	int
	updated_age	int
	Full Name	str
	new column	int
	double age	int
	char a count	int
	double age2	float
	compare_age	int

Rows: 7

Data:
+------------+-----------+---------------+-----+-------------+----------------+
| First Name | Last Name |    Country    | age | updated_age |   Full Name    |
+------------+-----------+---------------+-----+-------------+----------------+
|    Bob     |   Smith   | United States |  24 |     576     |   Bob Smith    |
|   Alice    |  Williams |     Canada    |  23 |     529     | Alice Williams |
|  Malcolm   |    Jone   |    England    |  22 |     484     |  Malcolm Jone  |
|   Felix    |   Brown   | United States |  23 |     529     |  Felix Brown   |
|    Alex    |   Cooper  |     Poland    |  23 |     529     |  Alex Cooper   |
|    Tod     |  Campbell | United States |  22 |     484     |  Tod Campbell  |
|   Derek    |    Ward   |  Switzerland  |  25 |     625     |   Derek Ward   |
+------------+-----------+---------------+-----+-------------+----------------+
+------------+------------+--------------+-------------+-------------+
| new column | double age | char a count | double age2 | compare_age |
+------------+------------+--------------+-------------+-------------+
|     11     |    576     |      0       |    576.0    |      24     |
|     11     |    529     |      2       |    529.0    |      24     |
|     11     |    484     |      1       |    484.0    |      22     |
|     11     |    529     |      0       |    529.0    |      24     |
|     11     |    529     |      1       |    529.0    |      24     |
|     11     |    484     |      1       |    484.0    |      22     |
|     11     |    625     |      1       |    625.0    |      26     |
+------------+------------+--------------+-------------+-------------+
[7 rows x 11 columns]

In [49]:
scores = [51.88431180850828, 38.120861753439925, 38.683971207674425]
exp_f = map(lambda x :1.0 +  math.exp(-1 * x), scores)
print exp_f
for x in exp_f:
    print 1.0/float(x)

[1.0, 1.0, 1.0]
1.0
1.0
1.0


In [47]:
### compare two SFrame , count if elements from each SFrame is same 
## this is wrong appraoch 
# count = 0
# def num_count(number):
#     global count
#     if number == sf['age'] :
#         count += 1
#     return count    
# count = sf['compare_age'].apply(num_count)
# print count

### compare two SFrame , count if elements from each SFrame is same 
len(sf['compare_age'][sf['compare_age']==sf['age']])    # great discovery !!!

3

In [48]:
## must remember !!
# song_sf['love_count'] = song_sf[['release', 'title', 'artist_name']].apply(
#     lambda row: sum(x.lower().split().count('love') for x in row.values()))
# song_sf.topk('love_count').head(5)

In [50]:
sf = graphlab.SFrame({'a':[1,3,2,1],
                       'b':['a','c','b','b'],
                       'c':['x','y','z','y']})
#sf.sort('a',descending=False)  # ascending sort for sf['a']  #error:sort() got an unexpected keyword argument 'descending'
#sf.sort('a')    #sort() default is ascending
sf.sort('a', ascending=False)   # same as sf.topk('a')
#sf.topk('a')

Columns:
	a	int
	b	str
	c	str

Rows: 4

Data:
+---+---+---+
| a | b | c |
+---+---+---+
| 3 | c | y |
| 2 | b | z |
| 1 | a | x |
| 1 | b | y |
+---+---+---+
[4 rows x 3 columns]

In [51]:
sf = graphlab.SFrame({'id': range(1000)})
sf['value'] = -sf['id']
sf.topk('id', k=3)

Columns:
	id	int
	value	int

Rows: 3

Data:
+-----+-------+
|  id | value |
+-----+-------+
| 999 |  -999 |
| 998 |  -998 |
| 997 |  -997 |
+-----+-------+
[3 rows x 2 columns]

In [52]:
#convert SFrame to dictionary
import graphlab as gl
sf9 = gl.SFrame({'X1': ['cat', 'dog'], 'X2': [1, 2], 'X3': [3, 4]})
print sf9
sf99 = sf9.rename({'X1': 'word'})
sf99 = sf9.pack_columns(column_prefix='X', new_column_name='vector')  # .pack_columns(column_prefix='X', new_column_name='vector')
print sf99
df = sf99.to_dataframe().set_index('word')
#.to_dict(orient='dict')['vector']
result99 = df.to_dict(orient='dict')['vector']
print result99

+-----+----+----+
|  X1 | X2 | X3 |
+-----+----+----+
| cat | 1  | 3  |
| dog | 2  | 4  |
+-----+----+----+
[2 rows x 3 columns]

+------+--------+
| word | vector |
+------+--------+
| cat  | [1, 3] |
| dog  | [2, 4] |
+------+--------+
[2 rows x 2 columns]

{'dog': [2L, 4L], 'cat': [1L, 3L]}


In [1]:
#find min element in list
list_test = [4,5,6,3,8,2,9]
print "sorted list",sorted(list_test )

aaa = list_test.sort()  #not working so, Just use sorted(list_name , reverse=True)
print aaa
def min_n (list_num):
    minNum = list_num[0]
    count = 0
    for j in list_num[count+1 : len(list_num) + 1]:
        if j < minNum :
            minNum = j
    return minNum
print "min_n(list_test) :",min_n(list_test)
#sort list                     -> wroing answer

def sort_n(list_num1):
    for i in range(len(list_num1)-1):
            minNum = i
            minVal = list_num1[i]
            print "i:",i
            for j in range( i+1, len(list_num1)):
                #print "j",j
                if minVal > list_num1[j]:
                    minNum = j
                    minVal = list_num1[j]
#             temp = minVal                           #wrong results
#             minVal = list_num1[j]
#             list_num1[j] = temp
            temp = list_num1[i]
            list_num1[i] = list_num1[j]
            list_num1[j]  = temp
            print "minNum", minNum , "minVal",minVal
    return list_num1
print sort_n(list_test)
            

sorted list [2, 3, 4, 5, 6, 8, 9]
None
min_n(list_test) : 2
i: 0
minNum 0 minVal 2
i: 1
minNum 6 minVal 2
i: 2
minNum 6 minVal 3
i: 3
minNum 6 minVal 4
i: 4
minNum 6 minVal 5
i: 5
minNum 6 minVal 6
[9, 2, 3, 4, 5, 6, 8]


In [54]:
#tuple sort..
student_tuples = [
        ('john', 'A', 15),
        ('jane', 'B', 12),
        ('dave', 'B', 10),
]
print sorted(student_tuples, key=lambda student: student[2])    # 10,12,15 order asecending is default
print sorted(student_tuples, key=lambda student: student[2],reverse = True)  # reverse= True 

[('dave', 'B', 10), ('jane', 'B', 12), ('john', 'A', 15)]
[('john', 'A', 15), ('jane', 'B', 12), ('dave', 'B', 10)]


In [56]:
song_sf = gl.SFrame.read_csv('s3://dato-datasets/millionsong/song_data.csv',
                             column_type_hints = {'year' : int})

KeyError: 'No access key found. Please set the environment variable AWS_ACCESS_KEY_ID, or using graphlab.aws.set_credentials()'

In [57]:
%pdb

Automatic pdb calling has been turned ON


In [ ]:
## make SFrame to calculate answer....!!!
# false positive(predict :1 and actual:-1), false negative(predict :-1, actual :1)  
import graphlab as gl
from graphlab import SArray
count_k = 0
list_k = []
for k in range(len(actual_negative)):
    list_k.append(k+1)
print "list_k :",list_k
ids=SArray(data=list_k, dtype=int)
# ids = SArray(list_k)
actual_negative =  SArray(data = [-1,-1,1,1], dtype=int)
predict_positive = SArray(data = [1,-1,-1,1], dtype=int)
sframe_test = gl.SFrame({'id':ids,'actual_negative':actual_negative,'predict_positive':predict_positive })
print "sframe_test :\n",sframe_test

# joined = predict_positive.join(actual_negative)  #'error:SArray' object has no attribute 'join'
# print joined
## make ref from SFrame guidance..
# song_sf['love_count'] = song_sf['release', 'title', 'artist_name'].apply(
#     lambda row: sum(x.lower().split().count('love') for x in row.keys()))
#sframe_test['false_positive']=sframe_test['actual_negative','predict_positive'].apply(lambda row : x.count(1) for x in row.keys())
print len(sframe_test[(sframe_test['predict_positive']==1) and (sframe_test['actual_negative']==-1)])  #wrong result 2 : should be 1,
### imiport if cond1 & cond2 : & operation shoud be used in if condition1 & condition2
print len(sframe_test[(sframe_test['predict_positive']==1) & (sframe_test['actual_negative']==-1)])  #wawoo !!! it works,,,!!!!!!!
#print len(sframe_test[sframe_test['predict_positive']==1 & sframe_test['actual_negative']==-1])  #w/o () errors.
print len(sframe_test[(sframe_test['predict_positive'], sframe_test['actual_negative'])== (1, -1)]) #wrong result 3: shoud be 1.

#last step : convert SFrame to dictionary.


In [ ]:
#error !
def f(arg_1,arg_2):
    if arg_1 == 1 and arg_2 == -1:
        return 1
    else:
        return 0     
#suppose the first argument of function f is one of the column, say 'predict_positive' in sframe_test, then
sframe_test['new_col'] = sframe_test['predict_positive'].apply(lambda x:f(x,sframe_test[predict_positive]))

In [ ]:
#which returns 1 if the value for row[‘dog-dog’] is lower than that of the other columns, and 0 otherwise. 
#That is, returns 1 if this row is correctly classified by 1-nearest neighbors, and 0 otherwise
import graphlab
from graphlab import SFrame
dog_distances=graphlab.SFrame({'dog-automobile' : [41,46,42,45],'dog-bird' : [41,41,43,38],'dog-cat':[36,38,36,37],'dog-dog':[33,42.5,39,37]})
print dog_distances

In [ ]:
#return an SArray (a column of data) with a 1 for every correct row and a 0 for every incorrect one.
def is_dog_correct(row):
    truV = True
# if use row, it represent key(dog-automobile,..),value(41...) pair or dictionary..    
#     dictionary keys(), values() , when used row.keys() which represent dog-automobile, dog-bird...:
#     row.values() represent actual distance values.-> use this ..!!!
    for x in row.values():   
        print "element in row.values():",x
        print "row:",row
        print "row['dog-dog']",row['dog-dog']
        print "********************************"
        if x < row['dog-dog']:  #row['dog-dog'] represent distance value 
            print "if  ele:",x
            print "if row['dog-dog']:",row['dog-dog']
            truV=False
    if truV:
        return 1
    else:
        return 0
        
dog_distances.apply(is_dog_correct)
print dog_distances
    
    

In [ ]:
# del dog_distances['accuracy']
print dog_distances

In [ ]:
dog_distances.apply(is_dog_correct).sum()  #correct result with 2 !!!!

In [ ]:
import graphlab
from graphlab import SFrame
sf = SFrame({'id':[1,2,3],'val':['A','B','C'],'val2':[5,6,7]})
print sf

In [ ]:
print dog_distances


In [ ]:
## ref 
# features = ['grade',              # grade of the loan
#             'term',               # the term of the loan
#             'home_ownership',     # home ownership status: own, mortgage or rent
#             'emp_length',         # number of years of employment
#            ]
# loans['safe_loans'] = loans['bad_loans'].apply(lambda x : +1 if x==0 else -1)
# loans.remove_column('bad_loans')
# target = 'safe_loans'
# loans = loans[features + [target]]

In [ ]:
features={'dog-automobile',
          'dog-bird',
          'dog-cat',
          'dog-dog'}
new_list = []
for feature in features:
    print feature
    dog_distances_one_hot_encoded = dog_distances[feature].apply(lambda x: {x: 1}) 
    print "**",dog_distances_one_hot_encoded
    new_list.append(dog_distances_one_hot_encoded)
print "&&", new_list
print len(new_list)

In [ ]:
#print one of two return value of tuple.
def return_tuple_value():
    return 34, 50
print return_tuple_value()[0]
print return_tuple_value()[1]

In [ ]:
scores = graphlab.SArray([0.]*len(sf))
print scores.head(3)

In [63]:

sf['test']=sf['value'].apply(lambda x : x**2 if x%2 != 0 else x-1)
print sf

+----+-------+------+
| id | value | test |
+----+-------+------+
| 0  |   0   |  -1  |
| 1  |   -1  |  1   |
| 2  |   -2  |  -3  |
| 3  |   -3  |  9   |
| 4  |   -4  |  -5  |
| 5  |   -5  |  25  |
| 6  |   -6  |  -7  |
| 7  |   -7  |  49  |
| 8  |   -8  |  -9  |
| 9  |   -9  |  81  |
+----+-------+------+
[1000 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.


In [64]:
## Drop elements with positive test value.(keep only negative test value: keep elements while sf['test']<0 is true )
sf = sf[sf['test']<0]  
print sf

+----+-------+------+
| id | value | test |
+----+-------+------+
| 0  |   0   |  -1  |
| 2  |   -2  |  -3  |
| 4  |   -4  |  -5  |
| 6  |   -6  |  -7  |
| 8  |   -8  |  -9  |
| 10 |  -10  | -11  |
| 12 |  -12  | -13  |
| 14 |  -14  | -15  |
| 16 |  -16  | -17  |
| 18 |  -18  | -19  |
+----+-------+------+
[? rows x 3 columns]
Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
You can use len(sf) to force materialization.
