In [6]:
import numpy as np
import graphlab as gl
import random
test_list1 = np.arange(1,10)
print test_list1
test_list2= test_list.reshape(3,3)
print test_list2

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print test_list2[0,:-1]  #as for first row, reverse order from first to last(-1),which is not incl
print test_list[1,-2:-1] #[ 1 ,-2:-1] rever order from -2 to -1(not incl)

[1 2]
[5]
